### ISSUE TITLE
Broken by CURLI rework

### ISSUE THREAD

**Issue by jonathanstowe** [retupmoca/P6-Find-Bundled#3]
Hi,
@_INC has gone away and one should be using $_REPO.repo-chain now.

I'm just working on fixing some of my own modules in this regard at the moment,  but if it doesn't get fixed before I'll try and send a PR.

Thanks.

**Comment by retupmoca** [comment]
With the recent addition of %?RESOURCES to rakudo, this module is probably not very useful anymore - I recommend using %?RESOURCES if at all possible.

**Comment by jonathanstowe** [comment]
Hi,
absolutely.  I had hand-coded the bits to find a co-installed dynamic library in my own modules, and have just replaced all of this with three lines of code.

I'll close this as I am sure on top of this.
